Tokel fixes and improvements for nspv and customised build
TokelPlatform/tokel pull request #16
Opened 2021-09-19 17:43 UTC by dimxy

added build of tokeld, tokel-cli
Tokel chain params are passed in configure
nspv maxrecords param added to listunspent, listtransactions
missing cs_main locks fixed in nspv
nspv rate limiter allows N req/sec
new gettransactionsmany nspv method

2021-09-20 18:28 UTC, jmjatlanta requested changes
Most of these are just suggestions, although 1 may be an issue. See komodo_nSPV_fullnode.h line 175.

2021-09-20 18:28 UTC, jmjatlanta commented on src/bitcoin-cli.cpp
> +                  "  " + cliname + " [options] <command> [params]  " + _("Send command to ") + brandname + "\n" +
Suggestion: Use argv[0] instead of cliname

2021-09-20 18:28 UTC, jmjatlanta commented on src/init.h
> +extern std::atomic<bool> fRequestShutdown;
`extern` declaration in komodo_bitcoind.h does not include std::atomic (not part of this PR, but I thought I mention it)

2021-09-20 18:28 UTC, jmjatlanta commented on src/bitcoind.cpp
> +/*
Suggestion: Remove unused code. If it should remain (which is rare IMO), add comments as to why.

2021-09-20 18:28 UTC, jmjatlanta commented on src/cc/CCImportGateway.h
> +int64_t ImportGatewayVerify(char *refdepositaddr,uint256 oracletxid,int32_t claimvout,std::string refcoin,uint256 burntxid,const std::string deposithex,std::vector<uint8_t>proof,uint256 merkleroot,CP
My opinion: Methods with large numbers of parameters should be (1) documented in the declaration (2) considered for refactoring (could structs help?) (3) split into multiple lines to avoid horizontal scrolling in IDEs and PRs

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo.h
> +    AssertLockHeld(cs_main);
Consider adding EXCLUSIVE_LOCKS_REQUIRED(cs_main) to method signature to help with static analysis

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_DEX.h
> +    memset(priv.bytes,0,sizeof(priv));
Perhaps a good use of RAII style destruction could be used here. Maybe a `secure` templated class that zeros out on destruction. Something like...
```
template<class T>
class secure
{
private:
   T _value;
public:
   secure(T val) : _value(val) {}
   ~secure() { memset(_value, 0, sizeof(_value)); }
   T &value() { return _value; }
};
```
Totally untested, and probably only useful if this could also be used elsewhere.

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_DEX.h
> +    memset(hash.bytes,0,sizeof(hash));
Is a hash of a private key dangerous, so as to need to be cleared out before destruction?

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_DEX.h
> +uint8_t *komodo_DEX_encrypt(uint8_t **allocatedp,uint8_t *data,int32_t *datalenp,bits256 destpubkey,bits256 privkey)
`allocatedp` looks to be freed in the right places, but would certainly be a good candidate for RAII style destruction (std::vector<uint8_t> perhaps? std::shared_ptr?)

2021-09-20 18:28 UTC, jmjatlanta commented on src/util.cpp
> +#include "komodo_defs.h"  // plz dont add this where it is not used, we have build errors for komodo-cli. Looks like it builds okay now
Perhaps this comment should be removed, as it seems to be no longer important.

2021-09-20 18:28 UTC, jmjatlanta commented on src/miner.cpp
> +extern CCriticalSection cs_metrics;
Consider hiding nHashCount within metrics and providing methods to query or increment the value, hiding locking behind the interface.

2021-09-20 18:28 UTC, jmjatlanta commented on configure.ac
> +echo "  CUSTOM_NAME       = $CUSTOM_NAME"
What does `CUSTOM_NAME` do? Where is it set? It doesn't seem to do affect anything.

2021-09-20 18:28 UTC, jmjatlanta commented on src/rpc/server.cpp
> +        return "> " + std::string(CUSTOM_BIN_NAME) + "-cli" + " " + methodname + " " + args + "\n";
Minor nits:
- Line 879: If we're going to use strprintf, why not go all the way (I know this particular line was not part of this PR, but it is close).
Suggestion: `return strprintf("> komodo-cli -ac_name=%s %s %s\n", ASSETCHAINS_SYMBOL, methodname, args);`
- Line 882: Setting the first as a string will mean all char*s after that will be appended as strings.
Suggestion: `return std::string("> ") + CUSTOM_BIN_NAME + "-cli " + methodname + " " + args + "\n";` or `return strprintf("> %s -cli %s %s\n", CUSTOM_BIN_NAME, methodname, args);`

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_defs.h
> +uint32_t komodo_heightstamp(int32_t height);
Already declared on line 570

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_defs.h
> +int32_t komodo_longestchain();
Already declared on line 560

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_defs.h
> +extern char ASSETCHAINS_SYMBOL[KOMODO_ASSETCHAIN_MAXLEN];
Already declared on line 497

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_defs.h
> +extern uint64_t ASSETCHAINS_ENDSUBSIDY[ASSETCHAINS_MAX_ERAS + 1], ASSETCHAINS_REWARD[ASSETCHAINS_MAX_ERAS + 1], ASSETCHAINS_HALVING[ASSETCHAINS_MAX_ERAS + 1];
ASSETCHAINS_REWARD already declared on line 509

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_defs.h
> +extern uint32_t ASSETCHAINS_MAGIC;
Already declared on line 499

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_defs.h
> +extern uint64_t ASSETCHAINS_LINEAR, ASSETCHAINS_COMMISSION, ASSETCHAINS_SUPPLY;
ASSETCHAINS_COMMISSION already declared on line 507 and ASSETCHAINS_SUPPLY on line 501

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_defs.h
> +extern uint8_t ASSETCHAINS_PUBLIC, ASSETCHAINS_PRIVATE;
ASSETCHAINS_PUBLIC already declared on line 494 and ASSETCHAINS_PRIVATE on line 533

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_defs.h
> +extern int32_t ASSETCHAINS_STAKED;
Already declared on line 506

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_defs.h
> +extern std::string ASSETCHAINS_OVERRIDE_PUBKEY;
Already declared on line 513

2021-09-20 18:28 UTC, jmjatlanta commented on src/rpc/server.h
> +extern void TxToJSON(const CTransaction& tx, const uint256 hashBlock, UniValue& entry);
no need for the `extern` keyword on function declarations

2021-09-20 18:28 UTC, jmjatlanta commented on src/komodo_nSPV_fullnode.h
> +        if ((pindex2 = komodo_chainactive(ptr->notarization.txidheight)) != 0)
Should `ptr->notarization.timestamp` be set to `nTime` of `pindex` or `pindex2`?

2021-09-21 13:59 UTC, dimxy commented on src/bitcoin-cli.cpp
> +                  "  " + cliname + " [options] <command> [params]  " + _("Send command to ") + brandname + "\n" +
I introduced new vars 'cliname' 'daemonname' which can be overridden from configure and makefile.am to build customised executable names like 'tokel-cli' 'tokeld' with burned into chain params

2021-09-21 14:02 UTC, dimxy commented on src/komodo_defs.h
> +extern uint8_t ASSETCHAINS_PUBLIC, ASSETCHAINS_PRIVATE;
I removed many repeating komodo declarations from sources into komodo_defs.h and could have added twice some, thank you, will clean this.

2021-09-21 14:10 UTC, dimxy commented on src/komodo_nSPV_fullnode.h
> +        if ((pindex2 = komodo_chainactive(ptr->notarization.txidheight)) != 0)
it seems you are right, should be pindex2, great catch!

2021-09-21 14:13 UTC, dimxy commented on src/cc/CCImportGateway.h
> +int64_t ImportGatewayVerify(char *refdepositaddr,uint256 oracletxid,int32_t claimvout,std::string refcoin,uint256 burntxid,const std::string deposithex,std::vector<uint8_t>proof,uint256 merkleroot,CP
It should be refactored indeed, f.e. taddr prefix prefix2 go together everywhere so could be placed in a struct.
I am not ready to refactor it here and it is disabled in this chain. Let's fix it in the dev branch first

2021-09-21 14:29 UTC, dimxy commented on src/komodo_DEX.h
> +    memset(priv.bytes,0,sizeof(priv));
good idea, 
I could see for such kind of data there exists special code locking pages in memory (pagelocker.h)
I suggest first add it in the dev branch

2021-09-21 14:30 UTC, dimxy commented on configure.ac
> +echo "  CUSTOM_NAME       = $CUSTOM_NAME"
now unused var, removing...

2021-09-21 14:32 UTC, dimxy commented on src/rpc/server.cpp
> +        return "> " + std::string(CUSTOM_BIN_NAME) + "-cli" + " " + methodname + " " + args + "\n";
maybe even better to change this to string stream

2021-09-21 14:34 UTC, dimxy commented on src/komodo_DEX.h
> +uint8_t *komodo_DEX_encrypt(uint8_t **allocatedp,uint8_t *data,int32_t *datalenp,bits256 destpubkey,bits256 privkey)
agree, suggesting first fix it in the dev branch

2021-09-21 14:39 UTC, dimxy commented on src/komodo_DEX.h
> +    memset(hash.bytes,0,sizeof(hash));
not sure, but seems dex priv key is derived from the hash.
i think we should move all such experimental code into a new branch or existing research branch

2021-09-21 15:26 UTC, dimxy commented on src/komodo.h
> +    AssertLockHeld(cs_main);
As can see EXCLUSIVE_LOCKS_REQUIRED or AssertLockHeld is used but not both.
Does AssertLockHeld presence help with analysis?

2021-09-21 15:29 UTC, dimxy commented on src/miner.cpp
> +extern CCriticalSection cs_metrics;
in the dev branch first?

2021-09-21 17:00 UTC, closed without merging